### ISSUE TITLE
pushwoosh error, is not finding functions of java

### ISSUE THREAD

**Issue by iccunha** [Pushwoosh/pushwoosh-xamarin#6]
My project Xamarin android, is not finding the functions of java embodied in PushWooshSDK.Droid project, I added the references and tried to compile both projects, and tried to rebuild PushWooshSDK.Droid

[printScreen project](http://prntscr.com/bn2so6)
[printScreen erros](http://prntscr.com/bn2v1d)

**Comment by DimanAM** [comment]
Do you have the same problem with [Pushwoosh Sample Project](https://github.com/Pushwoosh/pushwoosh-xamarin/tree/master/Android/PushwooshSample)?

**Comment by iccunha** [comment]
yes, I followed all the tutorial site...

**Comment by DimanAM** [comment]
This is strange. I cannot reproduce this with Xamarin Studio 6.0.1 (build 8). What version do you use?
You can also try https://github.com/Pushwoosh/pushwoosh-xamarin/commit/9463403b779f213491f6fe31933f863f4f37f4ce this commit uses uses jar library instead of aar.

**Comment by jerone** [comment]
@iccunha Did you solve this issue? I'm having the same issue right now :cry:

**Comment by JelleDamen** [comment]
Same issue here, also in the Sample project

**Comment by JelleDamen** [comment]
I tried building the PushWooshSDK.Droid myself in the sample project, it resulted in 0 errors, but a lot of warnings that look like this:

.../pushwoosh-xamarin/Android/PushwooshSDK/JARTOXML: Warning J2X9001: Couldn't load class com/pushwoosh/BaseRegistrationReceiver : java.lang.UnsupportedClassVersionError: android/content/BroadcastReceiver : Unsupported major.minor version 52.0 (J2X9001) (PushwooshSDK.Droid)

When googling on that error, it had something to do with the version of the Java JDK. On my machine was an older version (1.7...) after updating the Java JDK to 1.8.111 the project builded correctly, this also resolved the issue for me.

**Comment by DottorPagliaccius** [comment]
Same issue here, I can't compile the Android Project. I've the latest Java sdk, 1.8.121

**Comment by JelleDamen** [comment]
Try a clean on the project, remove all Obj folders and try building again.

**Comment by DottorPagliaccius** [comment]
Already tried, I cleaned everything, reinstalled java jdk, closed xamarin studio and restarted pc. You should really push this to nuget to avoid these issues (I was thinking about doing it myself, but I'm unsure if I legally can).

**Comment by JelleDamen** [comment]
Btw, make sure you have the JDK installed, not (only) the runtime.

http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

**Comment by DottorPagliaccius** [comment]
**dk-8u121-macosx-x64.dmg** for macOS, the sdk I just reinstalled... maybe the configured path in Xamarin Studio is wrong? I've the standard _"/usr"_ right now.

**Comment by JelleDamen** [comment]
I got that same configured path. Could you maybe share the error's that you're getting?

**Comment by DottorPagliaccius** [comment]
same as @iccunha: PW project compiles without errors but with 59 warnings, it doesn't expose types so main project doesn't compiles. 

warnings are like 

> .../PushWoosh/Android/PushwooshSDK/JARTOXML: Warning J2X9001: Couldn't load class com/pushwoosh/fragment/PushFragment : java.lang.NoClassDefFoundError: android/support/v4/app/Fragment (J2X9001) (PushwooshSDK.Droid)
> 
> .../PushWoosh/Android/PushwooshSDK/JARTOXML: Warning J2X9001: Couldn't load class com/pushwoosh/GCMInstanceIDListenerService : java.lang.NoClassDefFoundError: com/google/android/gms/iid/InstanceIDListenerService (J2X9001) (PushwooshSDK.Droid)

and so on...

**Comment by JelleDamen** [comment]
sorry, no clue. Maybe try to ask/search on stackoverflow.

**Comment by matheusgveras** [comment]
Same issue here

**Comment by shaders** [comment]
This class comes from Android SDK "java.lang.NoClassDefFoundError: android/support/v4/app/Fragment" - do you have android SDK installed and available in path for Xamarin Studio?

**Comment by DimanAM** [comment]
Pushwoosh SDKs are now available as nuget packages: 
https://www.nuget.org/packages/Pushwoosh.Xamarin.Droid/
https://www.nuget.org/packages/Pushwoosh.Xamarin.iOS/
I think this should help.

**Comment by DottorPagliaccius** [comment]
Thank God! ;)
